#!/bin/bash

# GBC Token Deployment Guide for Polygon Amoy Testnet
# =====================================================

echo "🚀 GBC Token Deployment Guide"
echo "=============================="
echo ""

# Step 1: Check requirements
echo "📋 Step 1: Prerequisites"
echo "------------------------"
echo "✓ GBCToken.sol contract exists"
echo "✓ hardhat.config.js configured"
echo "✓ deploy-gbc.js deployment script ready"
echo ""
echo "⚠️  You need:"
echo "   1. MetaMask wallet with private key"
echo "   2. Test MATIC from faucet"
echo "   3. Polygonscan API key (optional, for verification)"
echo ""

# Step 2: Install dependencies
echo "📦 Step 2: Install Hardhat Dependencies"
echo "---------------------------------------"
echo "Run this command:"
echo "  npm install --save-dev hardhat @nomicfoundation/hardhat-toolbox dotenv"
echo ""
read -p "Press Enter after installing dependencies..."
echo ""

# Step 3: Setup environment
echo "⚙️  Step 3: Setup Environment Variables"
echo "--------------------------------------"
echo "1. Copy .env.example to .env.local:"
echo "   cp .env.example .env.local"
echo ""
echo "2. Edit .env.local and add:"
echo "   PRIVATE_KEY=your_wallet_private_key_without_0x"
echo "   POLYGONSCAN_API_KEY=your_api_key (optional)"
echo "   GAME_SERVER_ADDRESS=server_wallet_address (optional)"
echo ""
echo "🔗 Get test MATIC: https://faucet.polygon.technology/"
echo "🔗 Get Polygonscan key: https://polygonscan.com/myapikey"
echo ""
read -p "Press Enter after setting up .env.local..."
echo ""

# Step 4: Compile contracts
echo "🔨 Step 4: Compile Smart Contract"
echo "-----------------------------------"
echo "Run this command:"
echo "  npx hardhat compile"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 5: Deploy
echo "🚀 Step 5: Deploy to Polygon Amoy"
echo "----------------------------------"
echo "Run this command:"
echo "  npx hardhat run scripts/deploy-gbc.js --network polygonAmoy"
echo ""
echo "Expected output:"
echo "  ✅ GBCToken deployed to: 0x..."
echo "  💎 Initial supply: 10000000.0 GBC"
echo "  🔍 Contract verified on Polygonscan"
echo ""
read -p "Press Enter after successful deployment..."
echo ""

# Step 6: Update config
echo "⚙️  Step 6: Update Frontend Configuration"
echo "----------------------------------------"
echo "Copy the deployed contract address and add to .env.local:"
echo "  NEXT_PUBLIC_GBC_TOKEN_ADDRESS=0x..."
echo ""
read -p "Press Enter after updating .env.local..."
echo ""

# Step 7: Import to MetaMask
echo "🦊 Step 7: Import GBC Token to MetaMask"
echo "---------------------------------------"
echo "1. Open MetaMask"
echo "2. Switch to Polygon Amoy Testnet"
echo "3. Click 'Import tokens'"
echo "4. Paste contract address"
echo "5. Token Symbol: GBC"
echo "6. Decimals: 18"
echo ""
echo "You should see your 10,000,000 GBC balance!"
echo ""

# Summary
echo "✅ Deployment Complete!"
echo "======================="
echo ""
echo "📝 Next steps:"
echo "1. Test wallet connection in app"
echo "2. Create useGBCBalance hook"
echo "3. Integrate with game mechanics"
echo "4. Test minting rewards on game win"
echo ""
echo "🎮 Contract Functions:"
echo "   - mintGameReward(address, amount) - Reward winners"
echo "   - burnGameLoss(amount) - Deduct bets"
echo "   - addGameMinter(address) - Authorize game server"
echo ""
echo "🔗 Useful Links:"
echo "   Polygon Amoy Explorer: https://amoy.polygonscan.com"
echo "   Faucet: https://faucet.polygon.technology"
echo "   Hardhat Docs: https://hardhat.org/docs"
echo ""
